<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="12" total="18" passed="3" failed="1" skipped="2">
  <reporter-output>
  </reporter-output>
  <suite started-at="2021-04-19T05:37:47Z" name="Suite" finished-at="2021-04-19T05:38:36Z" duration-ms="49338">
    <groups>
    </groups>
    <test started-at="2021-04-19T05:37:47Z" name="API Test" finished-at="2021-04-19T05:38:36Z" duration-ms="49338">
      <class name="TestCases.Send_OTP">
        <test-method is-config="true" signature="setup()[pri:0, instance:TestCases.Send_OTP@4aa83f4f]" started-at="2021-04-19T11:07:46Z" name="setup" finished-at="2021-04-19T11:07:46Z" duration-ms="176" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method is-config="true" signature="configure()[pri:0, instance:TestCases.Send_OTP@4aa83f4f]" started-at="2021-04-19T11:07:46Z" name="configure" finished-at="2021-04-19T11:07:47Z" depends-on-methods="com.MSIL.Setup.BaseSetup.setup" duration-ms="1042" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- configure -->
        <test-method is-config="true" signature="beforeTest(java.lang.String)[pri:0, instance:TestCases.Send_OTP@4aa83f4f]" started-at="2021-04-19T11:07:47Z" name="beforeTest" finished-at="2021-04-19T11:07:47Z" duration-ms="7" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[QA]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeTest -->
        <test-method is-config="true" signature="beforClass()[pri:0, instance:TestCases.Send_OTP@4aa83f4f]" started-at="2021-04-19T11:07:47Z" name="beforClass" finished-at="2021-04-19T11:07:47Z" duration-ms="7" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforClass -->
        <test-method is-config="true" signature="beforeMethod()[pri:0, instance:TestCases.Send_OTP@4aa83f4f]" started-at="2021-04-19T11:07:47Z" name="beforeMethod" finished-at="2021-04-19T11:07:47Z" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method signature="s_otp(java.util.Hashtable)[pri:0, instance:TestCases.Send_OTP@4aa83f4f]" started-at="2021-04-19T11:07:47Z" name="s_otp" data-provider="dp" finished-at="2021-04-19T11:07:52Z" duration-ms="4606" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[{mobileNo=, appId=4.0, endpoint=qa/sendotp}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- s_otp -->
        <test-method is-config="true" signature="afterMethod()[pri:0, instance:TestCases.Send_OTP@4aa83f4f]" started-at="2021-04-19T11:07:52Z" name="afterMethod" finished-at="2021-04-19T11:07:52Z" duration-ms="483" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method is-config="true" signature="afterSuite()[pri:0, instance:TestCases.Send_OTP@4aa83f4f]" started-at="2021-04-19T11:08:36Z" name="afterSuite" finished-at="2021-04-19T11:08:36Z" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterSuite -->
      </class> <!-- TestCases.Send_OTP -->
      <class name="TestCases.generateToken">
        <test-method is-config="true" signature="beforClass()[pri:0, instance:TestCases.generateToken@260e86a1]" started-at="2021-04-19T11:07:52Z" name="beforClass" finished-at="2021-04-19T11:07:52Z" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforClass -->
        <test-method signature="gen_auth_token(java.util.Hashtable, org.testng.ITestContext)[pri:0, instance:TestCases.generateToken@260e86a1]" started-at="2021-04-19T11:07:52Z" name="gen_auth_token" data-provider="dp" finished-at="2021-04-19T11:07:57Z" duration-ms="4554" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[{mobileNo=9169193968, otp=, appId=4, endpoint=qa/api/account/otp/authtoken}]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[org.testng.TestRunner@6a09484c]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- gen_auth_token -->
        <test-method is-config="true" signature="beforeMethod()[pri:0, instance:TestCases.generateToken@260e86a1]" started-at="2021-04-19T11:07:52Z" name="beforeMethod" finished-at="2021-04-19T11:07:52Z" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method is-config="true" signature="afterMethod()[pri:0, instance:TestCases.generateToken@260e86a1]" started-at="2021-04-19T11:07:57Z" name="afterMethod" finished-at="2021-04-19T11:07:57Z" duration-ms="132" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
      </class> <!-- TestCases.generateToken -->
      <class name="TestCases.Vehicle_Details_TC">
        <test-method is-config="true" signature="beforClass()[pri:0, instance:TestCases.Vehicle_Details_TC@12bd8a64]" started-at="2021-04-19T11:08:35Z" name="beforClass" finished-at="2021-04-19T11:08:35Z" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforClass -->
        <test-method is-config="true" signature="beforeMethod()[pri:0, instance:TestCases.Vehicle_Details_TC@12bd8a64]" started-at="2021-04-19T11:08:35Z" name="beforeMethod" finished-at="2021-04-19T11:08:35Z" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method signature="Vehicle_details(java.util.Hashtable, org.testng.ITestContext)[pri:0, instance:TestCases.Vehicle_Details_TC@12bd8a64]" started-at="2021-04-19T11:08:35Z" name="Vehicle_details" data-provider="dp" finished-at="2021-04-19T11:08:36Z" duration-ms="1442" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[{mileageCode=1000, tenureId=48, expectedErrorCode=200, variantCode=VBR4BZ1, resolution=xhdpi, categoryId=5, cityId=5, colorType=M, registrationType=WHITE_PLATE, modelCode=VB, partnerId=103, expectedMessage=, endpoint=qa/api/subscribe/vehicle/v2/detail}]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[org.testng.TestRunner@6a09484c]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Vehicle_details -->
        <test-method is-config="true" signature="afterMethod()[pri:0, instance:TestCases.Vehicle_Details_TC@12bd8a64]" started-at="2021-04-19T11:08:36Z" name="afterMethod" finished-at="2021-04-19T11:08:36Z" duration-ms="53" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
      </class> <!-- TestCases.Vehicle_Details_TC -->
      <class name="TestCases.Customer_Register_Cognito">
        <test-method is-config="true" signature="beforClass()[pri:0, instance:TestCases.Customer_Register_Cognito@19648c40]" started-at="2021-04-19T11:07:57Z" name="beforClass" finished-at="2021-04-19T11:07:57Z" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforClass -->
        <test-method is-config="true" signature="beforeMethod()[pri:0, instance:TestCases.Customer_Register_Cognito@19648c40]" started-at="2021-04-19T11:07:57Z" name="beforeMethod" finished-at="2021-04-19T11:07:57Z" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method signature="customer_register_cognito(java.util.Hashtable, org.testng.ITestContext)[pri:0, instance:TestCases.Customer_Register_Cognito@19648c40]" started-at="2021-04-19T11:07:57Z" name="customer_register_cognito" data-provider="dp" finished-at="2021-04-19T11:08:35Z" duration-ms="37752" status="SKIP">
          <params>
            <param index="0">
              <value>
                <![CDATA[{uuid=, mobile=1, businessType=SUBSCRIBE, referralCode=, expectedErrorCode=200, referredBy=, occupationTypeCode=, middleName=Kumar, email=gurender.kush@nagarro.com, expectedMessage=Customer successfully registered, gender=M, dob=1983-10-26, firstName=Gurender, lastName=Kush, endpoint=qa/customer/api/v1/user/register}]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[org.testng.TestRunner@6a09484c]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Customer successfully registered] but found [null]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Customer successfully registered] but found [null]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertEqualsImpl(Assert.java:129)
	at org.testng.Assert.assertEquals(Assert.java:115)
	at org.testng.Assert.assertEquals(Assert.java:189)
	at org.testng.Assert.assertEquals(Assert.java:199)
	at com.MSIL.TestUtils.Verify_Response.verify_Response(Verify_Response.java:25)
	at com.MSIL.API_LISTS.Common_Customer_Register_Cognito.common_customer_registercognito_API(Common_Customer_Register_Cognito.java:39)
	at TestCases.Customer_Register_Cognito.customer_register_cognito(Customer_Register_Cognito.java:22)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- customer_register_cognito -->
        <test-method is-config="true" signature="afterMethod()[pri:0, instance:TestCases.Customer_Register_Cognito@19648c40]" started-at="2021-04-19T11:08:35Z" name="afterMethod" finished-at="2021-04-19T11:08:35Z" duration-ms="68" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method signature="customer_register_cognito(java.util.Hashtable, org.testng.ITestContext)[pri:0, instance:TestCases.Customer_Register_Cognito@19648c40]" started-at="2021-04-19T11:08:35Z" name="customer_register_cognito" data-provider="dp" finished-at="2021-04-19T11:08:35Z" duration-ms="3" status="SKIP">
          <params>
            <param index="0">
              <value>
                <![CDATA[{uuid=, mobile=1, businessType=SUBSCRIBE, referralCode=, expectedErrorCode=200, referredBy=, occupationTypeCode=, middleName=Kumar, email=gurender.kush@nagarro.com, expectedMessage=Customer successfully registered, gender=M, dob=1983-10-26, firstName=Gurender, lastName=Kush, endpoint=qa/customer/api/v1/user/register}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.IllegalArgumentException">
            <message>
              <![CDATA[wrong number of arguments]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.IllegalArgumentException: wrong number of arguments
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.retryFailed(Invoker.java:1014)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1215)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.IllegalArgumentException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- customer_register_cognito -->
        <test-method is-config="true" signature="beforeMethod()[pri:0, instance:TestCases.Customer_Register_Cognito@19648c40]" started-at="2021-04-19T11:08:35Z" name="beforeMethod" finished-at="2021-04-19T11:08:35Z" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method is-config="true" signature="afterMethod()[pri:0, instance:TestCases.Customer_Register_Cognito@19648c40]" started-at="2021-04-19T11:08:35Z" name="afterMethod" finished-at="2021-04-19T11:08:35Z" duration-ms="85" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method is-config="true" signature="beforeMethod()[pri:0, instance:TestCases.Customer_Register_Cognito@19648c40]" started-at="2021-04-19T11:08:35Z" name="beforeMethod" finished-at="2021-04-19T11:08:35Z" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method signature="customer_register_cognito(java.util.Hashtable, org.testng.ITestContext)[pri:0, instance:TestCases.Customer_Register_Cognito@19648c40]" started-at="2021-04-19T11:08:35Z" name="customer_register_cognito" data-provider="dp" finished-at="2021-04-19T11:08:35Z" duration-ms="3" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[{uuid=, mobile=1, businessType=SUBSCRIBE, referralCode=, expectedErrorCode=200, referredBy=, occupationTypeCode=, middleName=Kumar, email=gurender.kush@nagarro.com, expectedMessage=Customer successfully registered, gender=M, dob=1983-10-26, firstName=Gurender, lastName=Kush, endpoint=qa/customer/api/v1/user/register}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.IllegalArgumentException">
            <message>
              <![CDATA[wrong number of arguments]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.IllegalArgumentException: wrong number of arguments
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.retryFailed(Invoker.java:1014)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1215)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.IllegalArgumentException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- customer_register_cognito -->
        <test-method is-config="true" signature="afterMethod()[pri:0, instance:TestCases.Customer_Register_Cognito@19648c40]" started-at="2021-04-19T11:08:35Z" name="afterMethod" finished-at="2021-04-19T11:08:35Z" duration-ms="66" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
      </class> <!-- TestCases.Customer_Register_Cognito -->
    </test> <!-- API Test -->
  </suite> <!-- Suite -->
</testng-results>
