<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="2" hostname="gurenderkush" name="TestCases.verify_vehicle_List_TC" tests="14" failures="0" timestamp="21 Sep 2021 15:12:40 GMT" time="6.794" errors="1">
  <testcase name="verify_list" time="0.441" classname="TestCases.verify_vehicle_List_TC"/>
  <testcase name="verify_list" time="0.535" classname="TestCases.verify_vehicle_List_TC"/>
  <testcase name="verify_list" time="0.434" classname="TestCases.verify_vehicle_List_TC"/>
  <testcase name="verify_list" time="0.527" classname="TestCases.verify_vehicle_List_TC"/>
  <testcase name="verify_list" time="0.545" classname="TestCases.verify_vehicle_List_TC"/>
  <testcase name="verify_list" time="0.810" classname="TestCases.verify_vehicle_List_TC"/>
  <testcase name="verify_list_city_invalid" time="0.316" classname="TestCases.verify_vehicle_List_TC"/>
  <testcase name="verify_list" time="0.444" classname="TestCases.verify_vehicle_List_TC"/>
  <testcase name="verify_list" time="0.467" classname="TestCases.verify_vehicle_List_TC"/>
  <testcase name="verify_list" time="1.173" classname="TestCases.verify_vehicle_List_TC"/>
  <testcase name="verify_list" time="0.501" classname="TestCases.verify_vehicle_List_TC">
    <skipped/>
  </testcase> <!-- verify_list -->
  <testcase name="verify_list" time="0.040" classname="TestCases.verify_vehicle_List_TC">
    <error type="java.lang.IllegalArgumentException" message="wrong number of arguments">
      <![CDATA[java.lang.IllegalArgumentException: wrong number of arguments
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.retryFailed(Invoker.java:1014)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1215)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- verify_list -->
  <testcase name="verify_list" time="0.041" classname="TestCases.verify_vehicle_List_TC">
    <skipped/>
  </testcase> <!-- verify_list -->
  <testcase name="verify_list" time="0.520" classname="TestCases.verify_vehicle_List_TC"/>
</testsuite> <!-- TestCases.verify_vehicle_List_TC -->
